=== vivekNarayanan/PropertyPublisher/PropPublishers/XslCreator/src/webapp/schema/BooksSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/BooksSchema"
	xmlns:bk="http://www.example.org/BooksSchema" elementFormDefault="qualified">
	<import schemaLocation="BooksSchema.xsd" namespace="http://www.example.org/BooksSchema"></import>
	<element name="bookstore">
		<complexType>
			<sequence>
				<element name="book" type="bk:book" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<complexType name="book">
		<sequence>
			<element name="category" type="string" />
			<element name="title" type="string" />
			<element name="author" type="string" />
			<element name="year" type="integer" />
			<element name="price" type="double" />
			<element name="editions" type="bk:editions" />
		</sequence>
	</complexType>
	<complexType name="editions">
		<sequence>
			<element name="edition" type="bk:edition" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="edition">
		<sequence>
			<element name="editionNumber" type="string" />
			<element name="references" type="string" />
		</sequence>
	</complexType>
</schema>

=== vivekNarayanan/PropertyPublisher/PropPublishers/XslCreator/src/webapp/xmlfiles/BooksSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<bk:bookstore xmlns:bk="http://www.example.org/BooksSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/BooksSchema ../schema/BooksSchema.xsd ">
	<bk:book>
		<bk:category>bk:category</bk:category>
		<bk:title>bk:title</bk:title>
		<bk:author>bk:author</bk:author>
		<bk:year>0</bk:year>
		<bk:price>0.0</bk:price>
		<bk:editions>
			<bk:edition>
				<bk:editionNumber>bk:editionNumber</bk:editionNumber>
				<bk:references>bk:references</bk:references>
			</bk:edition>
		</bk:editions>
	</bk:book>
</bk:bookstore>

=== vivekNarayanan/PropertyPublisher/PropPublishers/XslCreator/src/webapp/xmlfiles/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookstore xmlns:bk="http://www.example.org/BooksSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/BooksSchema ../schema/BooksSchema.xsd ">
	<book>
		<category>cooking</category>
		<title>Everyday Italian</title>
		<author>Giada De Laurentiis</author>
		<year>2005</year>
		<price>30.00</price>
		<editions>
			<edition>
				<editionNumber>1.0</editionNumber>
				<references>Borne Jason</references>
			</edition>
			<edition>
				<editionNumber>1.1</editionNumber>
				<references>Jason Statham</references>
			</edition>
		</editions>
	</book>
	<book>
		<category>children</category>
		<title>Harry Potter</title>
		<author>J K. Rowling</author>
		<year>2005</year>
		<price>29.99</price>
		<editions>
			<edition>
				<editionNumber>1.0</editionNumber>
				<references>Borne Jason</references>
			</edition>
			<edition>
				<editionNumber>1.1</editionNumber>
				<references>Jason Statham</references>
			</edition>
		</editions>
	</book>
	<book>
		<category>web</category>
		<title>Learning XML</title>
		<author>Erik T. Ray</author>
		<year>2003</year>
		<price>39.95</price>
		<editions>
			<edition>
				<editionNumber>1.0</editionNumber>
				<references>Borne Jason</references>
			</edition>
			<edition>
				<editionNumber>1.1</editionNumber>
				<references>Jason Statham</references>
			</edition>
		</editions>
	</book>
</bookstore>
